# -*- coding: utf-8 -*-
"""Datathon_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Puitwhma384pUUvvsxVV82_M4Pnedht
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Spotify_Music_modified.csv')

df.describe()

# Preview data
df.head(7)

df.tail(7)

# Shape of dataset
print("Shape:", df.shape)

# Column names
print("Columns:", df.columns)

# Data info
df.info()

if 'Unnamed: 0' in df.columns:
    df.drop(columns=['Unnamed: 0'], inplace=True)

df.isnull().sum()

df = df.dropna()

df.drop_duplicates(inplace=True)

df.reset_index(drop=True, inplace=True)

df.describe()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(6,4))
sns.histplot(df['popularity'], bins=30, kde=True)
plt.title('Distribution of Popularity')
plt.show()

plt.figure(figsize=(10,5))
df['track_genre'].value_counts().head(10).plot(kind='bar')
plt.title('Top 10 Genres')
plt.xlabel('Genre')
plt.ylabel('Count')
plt.show()

features = ['danceability','energy','valence','acousticness']

for col in features:
    plt.figure()
    sns.histplot(df[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.show()

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    plt.figure(figsize=(6,3))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.show()

numeric_cols_to_convert = ['popularity', 'duration_ms', 'danceability', 'energy', 'key', 'loudness', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature']

for col in numeric_cols_to_convert:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Select only numeric columns and drop any that are entirely NaN after coercion
df_numeric_for_corr = df.select_dtypes(include=np.number).dropna(axis=1, how='all')

if df_numeric_for_corr.empty:
    print("No numeric columns with valid (non-NaN) data found for correlation after conversion.")
else:
    plt.figure(figsize=(12,8))
    corr = df_numeric_for_corr.corr()
    sns.heatmap(corr, cmap='coolwarm', annot=False)
    plt.title('Correlation Heatmap')
    plt.show()

plt.figure()
sns.scatterplot(x='energy', y='popularity', data=df)
plt.title('Energy vs Popularity')
plt.show()

plt.figure()
sns.scatterplot(x='danceability', y='popularity', data=df)
plt.title('Danceability vs Popularity')
plt.show()

plt.figure()
sns.scatterplot(x='valence', y='popularity', data=df)
plt.title('Valence vs Popularity')
plt.show()

df['popularity_category'] = df['popularity'].apply(
    lambda x: 'High' if x > 70 else ('Medium' if x > 40 else 'Low')
)

sns.countplot(x='popularity_category', data=df)
plt.title('Popularity Categories')
plt.show()

